// Copyright (c) 2026 apebyte. All rights reserved. Part of Scenario Forge. Unauthorized use, copying, modification, or distribution is prohibited.

/**
 * @file Projectile.cpp
 * @brief Implements projectile customization, damage application, impact VFX, and destruction.
 */

#include "Projectile.h"

#include "Components/SphereComponent.h"
#include "Components/StaticMeshComponent.h"
#include "GameFramework/ProjectileMovementComponent.h"
#include "Kismet/GameplayStatics.h"
#include "Agent.h"
#include "ProjectileCustomization.h"

/**
 * @brief Initializes projectile collision, visual mesh, movement, and lifetime defaults.
 */
AProjectile::AProjectile()
{
	PrimaryActorTick.bCanEverTick = false;

	CollisionComponent = CreateDefaultSubobject<USphereComponent>(TEXT("CollisionComponent"));
	CollisionComponent->InitSphereRadius(2.0f);
	CollisionComponent->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
	CollisionComponent->SetCollisionObjectType(ECC_WorldDynamic);
	CollisionComponent->SetCollisionResponseToAllChannels(ECR_Block);
	CollisionComponent->OnComponentHit.AddDynamic(this, &AProjectile::HandleHit);
	SetRootComponent(CollisionComponent);

	StaticMeshComponent = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("StaticMeshComponent"));
	StaticMeshComponent->SetupAttachment(CollisionComponent);
	StaticMeshComponent->SetCollisionEnabled(ECollisionEnabled::NoCollision);

	ProjectileMovementComponent = CreateDefaultSubobject<UProjectileMovementComponent>(TEXT("ProjectileMovementComponent"));
	ProjectileMovementComponent->UpdatedComponent = CollisionComponent;
	ProjectileMovementComponent->InitialSpeed = 10000.0f;
	ProjectileMovementComponent->MaxSpeed = 10000.0f;
	ProjectileMovementComponent->ProjectileGravityScale = 0.0f;
	ProjectileMovementComponent->bRotationFollowsVelocity = true;
	ProjectileMovementComponent->bSweepCollision = true;

	InitialLifeSpan = 3.0f;
}

/**
 * @brief Applies projectile data from a customization asset.
 *
 * @param ProjectileCustomization Data asset containing projectile visuals, movement, damage, and VFX.
 */
void AProjectile::ApplyProjectileCustomization(const UProjectileCustomization* ProjectileCustomization)
{
	if (!ProjectileCustomization)
	{
		return;
	}

	if (CollisionComponent)
	{
		CollisionComponent->SetSphereRadius(ProjectileCustomization->CollisionRadius, true);
	}

	if (StaticMeshComponent)
	{
		StaticMeshComponent->SetStaticMesh(ProjectileCustomization->StaticMesh);
	}

	if (ProjectileMovementComponent)
	{
		ProjectileMovementComponent->InitialSpeed = ProjectileCustomization->InitialSpeed;
		ProjectileMovementComponent->MaxSpeed = ProjectileCustomization->MaxSpeed;
		ProjectileMovementComponent->ProjectileGravityScale = ProjectileCustomization->GravityScale;
	}

	InitialLifeSpan = ProjectileCustomization->MaxLifetime;
	Damage = ProjectileCustomization->Damage;
	ImpactVFX = ProjectileCustomization->ImpactVFX;
}

/**
 * @brief Handles valid projectile impacts against world actors.
 *
 * @param HitComponent Component on this projectile that generated the hit.
 * @param OtherActor Actor hit by the projectile.
 * @param OtherComponent Component hit on the other actor.
 * @param NormalImpulse Physics impulse generated by the hit.
 * @param Hit Detailed impact data including impact point and normal.
 */
void AProjectile::HandleHit(
	UPrimitiveComponent* HitComponent,
	AActor* OtherActor,
	UPrimitiveComponent* OtherComponent,
	FVector NormalImpulse,
	const FHitResult& Hit)
{
	if (!OtherActor || OtherActor == this || OtherActor == GetOwner() || OtherActor == GetInstigator())
	{
		return;
	}

	if (AAgent* HitAgent = Cast<AAgent>(OtherActor))
	{
		HitAgent->ApplyDamage(Damage, this);
	}

	/*
	TODO: Re-enable this diagnostic block when impact debugging is needed.

	const UStaticMeshComponent* HitStaticMeshComponent = Cast<UStaticMeshComponent>(OtherComponent);
	const FString HitMeshAssetName = HitStaticMeshComponent
		? GetNameSafe(HitStaticMeshComponent->GetStaticMesh())
		: TEXT("None");

	UE_LOG(
		LogTemp,
		Log,
		TEXT("AProjectile::HandleHit - Hit Actor: %s, Actor Class: %s, Component: %s, Mesh Asset: %s"),
		*GetNameSafe(OtherActor),
		*GetNameSafe(OtherActor->GetClass()),
		*GetNameSafe(OtherComponent),
		*HitMeshAssetName);
	*/

	if (ImpactVFX)
	{
		/** TODO: Pick impact VFX by the surface type we hit instead of always using one default effect. */
		UGameplayStatics::SpawnEmitterAtLocation(
			this,
			ImpactVFX,
			Hit.ImpactPoint,
			Hit.ImpactNormal.Rotation());
	}

	Destroy();
}
